### PR TITLE
Added sight checks to Mirror Image

### PR DESCRIPTION
**Pull request by SagaTympana**
Mirror Image doesn't function if the attacker can't see the target, relies on senses other than sight, or can perceive illusions, so I added returns if the attacker is blinded or the target is within the range of the attacker's blindsight or truesight.

### CODE REVIEW

**Comment by chrisk123999** [comment]
Why is there an early return for what looks like a blinded check?

**Comment by SagaTympana** [comment]
Because creatures that can't see are immune to Mirror Image.

**Comment by chrisk123999** [comment]
This pull request appears to be messed up. The files changed is adding a few empty lines.

**Comment by SagaTympana** [comment]
Yeah, I made some mistakes with the forking, still getting used to GitHub. I'm gonna close this PR and open a new, fixed one. Thank you for your patience as I find my footing with the process.

**Pull request closed without merging**
