### PR TITLE
Dev/sickening

### PR DESCRIPTION
**Pull request by ImproperSubset**
The chris-premades mod is great. I've really enjoyed the additional functionality. I learned a lot about Foundry development by looking through the code. Fantastic work. I've tried my hand at adding an implementation of Sickening Radiance. It gets used at my table weekly.

I based this on the implementation of Cloudkill. I think it follows the same rules interpretation concerning overlapping effects that was established there. It has some additional complexity in that there are effects that persist when the token leaves the AoE, but which end when the spell ends.

This version handles the exhaustion levels and adds a condition immunity for invisibility. The immunity doesn't seem to have a mechanical effect. It would be ideal if midi had a flag that made it so a token couldn't benefit from the invisibility condition. If it exists, I'm not sure what it is. It would be great for Faerie Fire and Sickening Radiance. It would be great to get it to add the the dim light effect as well, but ATL isn't declared as an optional module. Also, I gave it a try and I'm not sure how to get the token's light to update from a macro. It seems to work from the GUI, but there must be some update event I don't know about to get the canvas to add the change to dim light.

I've done some testing and I think it works. I did most of my testing a GM window. I did some testing using a player and GM window. That exposed at least one bug. I'm not sure what other kinds of testing would by typical. This is my first venture into Foundry module development.

### CODE REVIEW

**Comment by chrisk123999** [comment]
I'll look this over when I get a chance.  May be a few days however.

**Comment by ImproperSubset** [comment]
No problem. I'm in no hurry. Happy to make any changes you think are necessary. I tried to follow your formatting style, but I don't necessarily know enough about JS styles to recognize subtlety. If there's a formatter that you're using I'd be happy to reformat and conform to your repo's requirements.

**Comment by ImproperSubset** [comment]
Should I close this pull request? I'm still happy to make changes if you're concerned about it meeting your coding standards or you're concerned about some portion of the implementation. If you're not interested in unsolicited contributions , that's no problem. I'll just track this in a fork or maybe make a dependent module. CPR is a great contribution to the community and I appreciate the work you and your team have put into it.

**Comment by chrisk123999** [comment]
I've started work on a system to handle template based spells better.  This spell and a rewrite of Cloudkill are things I want to get to.

**Pull request closed without merging**
