### PR TITLE
Use Rideable grapple if active

### PR DESCRIPTION
**Pull request by txm3278**
Uses the grapple macro from [Rideable](https://github.com/Saibot393/Rideable#macros)

### CODE REVIEW

**Comment by chrisk123999** [comment]
It may be worthwhile to explicitly use `game.Rideable.Mount` and pass on the token and target from midi.

**Comment by txm3278** [comment]
I can test it, I know Mount and grapple are 2 different things within Rideable though

**Comment by txm3278** [comment]
Mount puts the token on top of the target, grapple keeps them next to each other. It seems like grapple is the way to go

**Comment by chrisk123999** [comment]
Looks like you can set it to be a grapple.

**Comment by txm3278** [comment]
Got it working with .Mount

**Pull request merged**
