### PR TITLE
Add limits flags to Darkvision

### PR DESCRIPTION
**Pull request by txm3278**
Adds a flag to the darkness template that blocks light perception and darkvision if the limits module is installed.

### CODE REVIEW

**Comment by chrisk123999** [comment]
Should likely be changed to a template update and combined with the other flags that get set on it to reduce database hits.

**Comment by txm3278** [comment]
Changed to a template update and should now block light as well

**Comment by txm3278** [comment]
Limits added a darkness example to it's [github](https://github.com/dev7355608/limits). I used those settings and tested it. Now includes spreading around walls if Walled Templates is installed.

**Comment by chrisk123999** [comment]
I've manually merged this pull.  It will be out in the next update as an untested addition.

**Pull request closed without merging**
